/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadora_correos;

import java.text.DecimalFormat;

/**
 *
 * @author alexf
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPeso = new javax.swing.JLabel();
        pesoCarta = new javax.swing.JSpinner();
        envio = new javax.swing.JComboBox<>();
        labelEnvio = new javax.swing.JLabel();
        certificado = new javax.swing.JCheckBox();
        recibo = new javax.swing.JCheckBox();
        valorDeclarado = new javax.swing.JCheckBox();
        jComboBox2 = new javax.swing.JComboBox<>();
        labelDestino = new javax.swing.JLabel();
        calculo = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        paquete = new javax.swing.JComboBox<>();
        labelPaquete = new javax.swing.JLabel();
        labelPrecioProducto = new javax.swing.JLabel();
        valor = new javax.swing.JSpinner();
        labelCertificado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        labelPeso.setText("Peso de la carta");

        pesoCarta.setModel(new javax.swing.SpinnerNumberModel(1, 1, 2000, 1));

        envio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Envio estandar", "Envio urgente" }));

        labelEnvio.setText("Tipo de envio");

        certificado.setLabel("Correo certificado");
        certificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certificadoActionPerformed(evt);
            }
        });

        recibo.setText("Acuse de recibo");
        recibo.setEnabled(false);

        valorDeclarado.setText("Valor declarado");
        valorDeclarado.setEnabled(false);
        valorDeclarado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                valorDeclaradoMouseClicked(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nacional" }));

        labelDestino.setText("Destino del envio");

        calcular.setText("Calcular");
        calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcularMouseClicked(evt);
            }
        });

        paquete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carta", "Tarjeta postal" }));

        labelPaquete.setText("Tipo de paquete");

        labelPrecioProducto.setText("Precio del producto");
        labelPrecioProducto.setVisible(false);

        valor.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3000, 50));
        valor.setVisible(false);

        labelCertificado.setText("Escoja si su correo es certificado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(certificado)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(recibo)
                                    .addComponent(valorDeclarado)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(labelPrecioProducto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(labelCertificado)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPaquete)
                                    .addComponent(paquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelEnvio)
                                    .addComponent(envio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDestino)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pesoCarta)
                                .addComponent(labelPeso)))
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calculo, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPaquete)
                            .addComponent(labelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(envio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(labelCertificado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(certificado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recibo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(labelPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(pesoCarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorDeclarado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrecioProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calculo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcular))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void certificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certificadoActionPerformed
        if (certificado.isSelected()) {
            recibo.setEnabled(true);
            valorDeclarado.setEnabled(true);
        } else {
            recibo.setEnabled(false);
            valorDeclarado.setEnabled(false);

            recibo.setSelected(false);
            valorDeclarado.setSelected(false);
        }
    }//GEN-LAST:event_certificadoActionPerformed

    private void calcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcularMouseClicked
        String sEnvio = envio.getSelectedItem().toString();
        String sPaquete = paquete.getSelectedItem().toString();
        int getPesoCarta = (int) pesoCarta.getValue();
        int precioValor = (int) valor.getValue();
        double resultado = 0;
        boolean sePasaDePeso = false;

        if (sEnvio.equals("Envio urgente") && certificado.isSelected()) {
            if (getPesoCarta <= 20) {
                resultado = 8.28;
            } else if (getPesoCarta > 20 && getPesoCarta <= 50) {
                resultado = 8.40;
            } else if (getPesoCarta > 50 && getPesoCarta <= 100) {
                resultado = 8.92;
            } else if (getPesoCarta > 100 && getPesoCarta <= 500) {
                resultado = 10.55;
            } else if (getPesoCarta > 500 && getPesoCarta <= 1000) {
                resultado = 14.00;
            } else if (getPesoCarta > 1000 && getPesoCarta <= 2000) {
                resultado = 14.58;
            } else {
                sePasaDePeso = true;
            }
        } else if (sEnvio.equals("Envio urgente")) {
            if (getPesoCarta <= 20) {
                resultado = 4.10;
            } else if (getPesoCarta > 20 && getPesoCarta <= 50) {
                resultado = 4.22;
            } else if (getPesoCarta > 50 && getPesoCarta <= 100) {
                resultado = 4.74;
            } else if (getPesoCarta > 100 && getPesoCarta <= 500) {
                resultado = 6.38;
            } else {
                sePasaDePeso = true;
            }
        } else if (sEnvio.equals("Envio estandar") && certificado.isSelected() && sPaquete.equals("Carta")) {
            if (getPesoCarta <= 20) {
                resultado = 4.15;
            } else if (getPesoCarta > 20 && getPesoCarta <= 50) {
                resultado = 4.25;
            } else if (getPesoCarta > 50 && getPesoCarta <= 100) {
                resultado = 4.70;
            } else if (getPesoCarta > 100 && getPesoCarta <= 500) {
                resultado = 5.95;
            } else if (getPesoCarta > 500 && getPesoCarta <= 1000) {
                resultado = 8.60;
            } else if (getPesoCarta > 1000 && getPesoCarta <= 2000) {
                resultado = 9.05;
            } else {
                sePasaDePeso = true;
            }
        } else if (sEnvio.equals("Envio estandar") && !certificado.isSelected()) {
            if (getPesoCarta <= 20) {
                resultado = 0.70;
            } else if (getPesoCarta > 20 && getPesoCarta <= 50) {
                resultado = 0.80;
            } else if (getPesoCarta > 50 && getPesoCarta <= 100) {
                resultado = 1.25;
            } else if (getPesoCarta > 100 && getPesoCarta <= 500) {
                resultado = 2.50;
            } else if (getPesoCarta > 500 && getPesoCarta <= 1000) {
                resultado = 5.15;
            } else if (getPesoCarta > 1000 && getPesoCarta <= 2000) {
                resultado = 5.60;
            } else {
                sePasaDePeso = true;
            }
        } else {
            sePasaDePeso = true;
        }

        if (recibo.isSelected()) {
            resultado = resultado + 1.94;
        }

        if (valorDeclarado.isSelected()) {
            precioValor = precioValor / 50;
            if (precioValor != 0) {
                resultado = resultado + 2.10 * precioValor;
            }
        }

        if (!sePasaDePeso) {
            DecimalFormat f = new DecimalFormat("#.##");

            calculo.setText("El precio del envio es de " + f.format(resultado));
        } else {
            calculo.setText("Introduce correctamente los valores");
        }
    }//GEN-LAST:event_calcularMouseClicked

    private void valorDeclaradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valorDeclaradoMouseClicked
        if (valorDeclarado.isSelected()) {
            labelPrecioProducto.setVisible(true);
            valor.setVisible(true);
        } else {
            labelPrecioProducto.setVisible(false);
            valor.setVisible(false);
        }
    }//GEN-LAST:event_valorDeclaradoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JLabel calculo;
    private javax.swing.JCheckBox certificado;
    private javax.swing.JComboBox<String> envio;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel labelCertificado;
    private javax.swing.JLabel labelDestino;
    private javax.swing.JLabel labelEnvio;
    private javax.swing.JLabel labelPaquete;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JLabel labelPrecioProducto;
    private javax.swing.JComboBox<String> paquete;
    private javax.swing.JSpinner pesoCarta;
    private javax.swing.JCheckBox recibo;
    private javax.swing.JSpinner valor;
    private javax.swing.JCheckBox valorDeclarado;
    // End of variables declaration//GEN-END:variables
}
